export const routes = [
  {
    source: "Delhi",
    destination: "Mumbai",
    startingTime: "08:00 AM",
    reachingTime: "01:00 PM",
  },
  {
    source: "Mumbai",
    destination: "Bangalore",
    startingTime: "09:00 AM",
    reachingTime: "02:00 PM",
  },
  {
    source: "Bangalore",
    destination: "Hyderabad",
    startingTime: "10:00 AM",
    reachingTime: "03:00 PM",
  },
  {
    source: "Hyderabad",
    destination: "Chennai",
    startingTime: "11:00 AM",
    reachingTime: "04:00 PM",
  },
  {
    source: "Chennai",
    destination: "Kolkata",
    startingTime: "12:00 PM",
    reachingTime: "05:00 PM",
  },
  {
    source: "Kolkata",
    destination: "Lucknow",
    startingTime: "01:00 PM",
    reachingTime: "06:00 PM",
  },
  {
    source: "Lucknow",
    destination: "Jaipur",
    startingTime: "02:00 PM",
    reachingTime: "07:00 PM",
  },
  {
    source: "Jaipur",
    destination: "Bhopal",
    startingTime: "03:00 PM",
    reachingTime: "08:00 PM",
  },
  {
    source: "Bhopal",
    destination: "Chandigarh",
    startingTime: "04:00 PM",
    reachingTime: "09:00 PM",
  },
  {
    source: "Chandigarh",
    destination: "Dehradun",
    startingTime: "05:00 PM",
    reachingTime: "10:00 PM",
  },
  {
    source: "Chennai",
    destination: "Bangalore",
    startingTime: "08:00 AM",
    reachingTime: "01:00 PM",
  },
  {
    source: "Chennai",
    destination: "Bangalore",
    startingTime: "09:00 AM",
    reachingTime: "02:00 PM",
  },
  {
    source: "Delhi",
    destination: "Manali",
    startingTime: "01:00 PM",
    reachingTime: "06:00 PM",
  },
  {
    source: "Delhi",
    destination: "Manali",
    startingTime: "02:00 PM",
    reachingTime: "07:00 PM",
  },
  {
    source: "Delhi",
    destination: "Manali",
    startingTime: "03:00 PM",
    reachingTime: "08:00 PM",
  },
  {
    source: "Pune",
    destination: "Mumbai",
    startingTime: "05:00 PM",
    reachingTime: "10:00 PM",
  },
  {
    source: "Pune",
    destination: "Mumbai",
    startingTime: "08:00 PM",
    reachingTime: "12:00 AM",
  },
  {
    source: "Lucknow",
    destination: "Jaipur",
    startingTime: "06:00 PM",
    reachingTime: "11:00 PM",
  },
];
